openapi: "3.1.0"
info:
  title: "craw API"
  description: "craw API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /graph:
    get:
      description: ""
  /record:
    options:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WebsiteRecordCreate"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /record/{id}:
    delete:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    get:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/WebsiteRecord"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
    options:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
    put:
      description: ""
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WebsiteRecordUpdate"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "object"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /records:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/WebsiteRecord"
    options:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    WebsiteRecordCreate:
      type: "object"
      properties:
        url:
          type: "string"
        regexp:
          type: "string"
        periodicity:
          type: "string"
        label:
          type: "string"
        active:
          type: "boolean"
        tags:
          type: "array"
          items:
            type: "string"
      required:
        - "url"
        - "regexp"
        - "periodicity"
        - "label"
        - "tags"
    Instant:
      type: "object"
      properties: { }
    WebsiteExecution:
      type: "object"
      properties:
        url:
          type: "string"
        start:
          $ref: "#/components/schemas/Instant"
        end:
          $ref: "#/components/schemas/Instant"
        title:
          type: "string"
        links:
          type: "array"
          items:
            type: "string"
      required:
        - "url"
        - "start"
        - "links"
    WebsiteRecord:
      type: "object"
      properties:
        recordId:
          type: "string"
        url:
          type: "string"
        regexp:
          type: "string"
        periodicity:
          type: "string"
        label:
          type: "string"
        active:
          type: "boolean"
        tags:
          type: "array"
          items:
            type: "string"
        executions:
          type: "array"
          items:
            $ref: "#/components/schemas/WebsiteExecution"
      required:
        - "recordId"
        - "url"
        - "regexp"
        - "periodicity"
        - "label"
        - "tags"
        - "executions"
    WebsiteRecordUpdate:
      type: "object"
      properties:
        recordId:
          type: "string"
        url:
          type: "string"
        regexp:
          type: "string"
        periodicity:
          type: "string"
        label:
          type: "string"
        active:
          type: "boolean"
        tags:
          type: "array"
          items:
            type: "string"
      required:
        - "recordId"