services:
  frontend:
    container_name: craw-frontend
    build: frontend
    ports:
      - "8081:80"
    environment:
      BACKEND_HOST: "backend:8080"
    networks:
      - craw
  backend:
    container_name: craw-backend
    build: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - craw
  db:
    image: postgres:alpine3.20
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
    networks:
      - craw

volumes:
  postgres_data:
    driver: local

networks:
  craw:
    driver: bridge